### ISSUE TITLE
More settings should be configurable

### ISSUE THREAD

**Issue by jamadden** [NextThought/nti.recipes.zodb#12]
We hard-code a pool-size, for example. We should have defaults but allow configuration.

**Comment by cutz** [comment]
@sajones had a set of things in his mind that we needed to be able to configure. `pool-size` being one of them.

**Comment by sajones** [comment]
@jamadden When attempting to use the new sqlite backend I was not able to find how to set the driver and gevent_yield_interval using this recipe. Nor was I able to configure cache-size to something other than 100000.

**Comment by jamadden** [comment]
Prior to PR #14, `cache-size` was not configurable.

Setting the driver for sqlite works the same as it does for all the other adapters, by setting the `sql_adapter_extra_args`. For example this buildout.cfg:

```ini
[buildout]
parts = relstorages
root-directory = /tmp/B

[relstorages]
recipe = nti.recipes.zodb:relstorage
storages = Users

[relstorages_opts]
sql_adapter = sqlite3
sql_adapter_extra_args =
    driver gevent sqlite3
```

Gives this /tmp/B/etc/zodb_conf.xml:

```xml
%import zc.zlibstorage
%import relstorage
<zodb Users>
  cache-size 100000
  database-name Users
  pool-size 60
  <zlibstorage Users>
    <relstorage Users>
        <sqlite3>
          # This comment preserves whitespace
          data-dir /tmp/B/data/relstorages_users_storage
          driver gevent sqlite3
        </sqlite3>
      blob-dir /tmp/B/data/Users.blobs
      cache-local-dir /tmp/B/var/caches/data_cache/Users.cache
      cache-local-mb 300
      cache-prefix Users
      commit-lock-timeout 60
      keep-history false
      name Users
      pack-gc false
      shared-blob-dir true
    </relstorage>
  compress false
</zlibstorage>
</zodb>
```

**Comment by jamadden** [comment]
(Not that this is in [any way documented](https://github.com/NextThought/nti.recipes.zodb/issues/13)].)
