### ISSUE TITLE
Add support for adding ZODB ``pool-timeout``

### ISSUE THREAD

**Issue by cutz** [NextThought/nti.recipes.zodb#19]
As far as I can tell there isn't a way to set the ZODB ``pool-timeout`` setting with this recipe.

Edit: pool_timeout... #16 added support for pool_size.

**Comment by jamadden** [comment]
I'd forgotten how complex this setup is, with all the potential layers of indirection.

This turns out to be a bit tricky to do because there's not necessarily a sensible default and the data model and templates aren't really set up to handle that. It'll take a bit of thought.

**Comment by cutz** [comment]
Yep, I ran into that which is why we got an issue and not a PR. I thought about just duplicating the default from ZODB here but that doesn't seem right.
